### ISSUE TITLE
Not matching on git shas

### ISSUE THREAD

**Issue by colindresj** [tmux-plugins/tmux-copycat#104]
Recently updated my tmux plugins (been a while since my last update), and for some reason `prefix + alt-h` after a `git log` no longer matches the git hashes. If I hit `n`, I get `"No previous regular expression (press RETURN)"`.  Any ideas?

**Comment by neilpeter08** [comment]
Experiencing the same issue too

**Comment by nguyenj** [comment]
I'm getting the same issue here too.

**Comment by chris-fa** [comment]
Just installed copycat, I'm experiencing this.

**Comment by florianbegusch** [comment]
@chris-fran #143 this should fix it. Could you give it a try?

**Comment by bruno-** [comment]
Just fixed matching sha256. Please reopen the issue if this is still a problem.
