### ISSUE TITLE
How to make alt key predefined searches work?

### ISSUE THREAD

**Issue by peterbollen** [tmux-plugins/tmux-copycat#110]
Hi, 

I can't figure out how make the `alt` key predefined searches work on my mac.

After echo-ing an ip in the terminal, 
pressing `prefix + alt-i` does not seem to trigger a search.

Fyi, `ctrl` key predefined searches are working.

Any tips?

**Comment by bennyty** [comment]
OSX maps alt-i to the ˆ character (MODIFIER LETTER CIRCUMFLEX ACCENT). In order to use the alt modifier you want the terminal to interpret alt as the "meta" modifier. iTerm2 and Terminal both have options for this. http://superuser.com/questions/496090/how-to-use-alt-commands-in-a-terminal-on-os-x

**Comment by peterbollen** [comment]
Thanks @bennyty , works as a charm!
