### ISSUE TITLE
How to make search of predefined case sensitive word list?

### ISSUE THREAD

**Issue by dominikduda** [tmux-plugins/tmux-copycat#111]
I would like to have a binding to search for defined list words.

This one works:
```
bind e run-shell "$HOME/.tmux/plugins/tmux-copycat/scripts/copycat_mode_start.sh '(Error|FATAL)'"
```

But I want to make it case sensitive (so `Error` will match but `error` will not).

Is there way to achieve it?

**Comment by thalesmello** [comment]
So, the pattern matching is done in this [line](https://github.com/tmux-plugins/tmux-copycat/blob/master/scripts/copycat_generate_results.sh#L20).

If notice, the `grep` command is called with the ignore case (`-i`) option.

If you want to distinguish between uppercase and lowercase, just remove it.

**Comment by dominikduda** [comment]
Thanks!
