### ISSUE TITLE
Not work on Tmux 2.5

### ISSUE THREAD

**Issue by TangMonk** [tmux-plugins/tmux-copycat#118]
When I typing: `C-a + C-f` not works, and cannot select as expected, please watch following video screen record:

https://www.dropbox.com/s/o4iqkkfnthfx8fg/tmux_2.5_problem.mov?dl=0

I am using fishshell 2.6 and tmux 2.5 on osx

**Comment by toupeira** [comment]
tmux 2.5 also broke my setup, some changes I noticed:

- the `-t` argument (to select a keymap table) is now `-T`
- the keymap tables were renamed (e.g. `vi-copy` is now `copy-mode-vi`)
- copy mode commands now need to be sent with `send-keys -X`, e.g. where before I could do `page-down` I now have to call `send-keys -X page-down`

**Comment by bruno-** [comment]
Hi,

the changes in tmux 2.4 broke this plugin. I have to find some time to make fixes. I've added a note about this to the readme.

**Comment by adamgotterer** [comment]
Any update on this?

**Comment by bruno-** [comment]
Hi, unfortunately no. The plugin works up to tmux version 2.3 and that's stated in the readme.

**Comment by laktak** [comment]
I have some scripts that can extract paths & urls from the buffer which you can then select via fzf. So it's not the same as copycat but it works quite well. If anyone is interested I can try to turn that into a plugin.

**Comment by maximbaz** [comment]
Before you turn those into a plugin, could you share the scripts so that we can try them out? 🙂

**Comment by oschrenk** [comment]
Everything that uses tmux and fzf tends to be a good thing

I’m not sure how much I can help myself but I’m interested.

**Comment by laktak** [comment]
@maximbaz @oschrenk you can take a look at it [here](https://github.com/laktak/extrakto)

**Comment by phye** [comment]
@laktak I have replaced tmux-copycat with your plugin as it seems to be more universal and less keys to remember 👍

**Comment by laktak** [comment]
@phye thanks, I had a ton of help from @ivanalejandro0 and @maximbaz though!

**Comment by oblitum** [comment]
@laktak awesome plugin 👌

**Comment by bruno-** [comment]
Closing this PR as this was addressed via #119

**Comment by oblitum** [comment]
So great and in the process extrakto was born 😊
