### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by peterdutton** [tmux-plugins/tmux-copycat#126]
Hi,

I can't seem to get the `prefix + /` search to work. When I try it, it won't highlight the term I searched for but it does put me into 'copy mode' so that I can navigate the scrollback to select something.

Please can you let me know how I might troubleshoot this? I am using the following:

`set -g @plugin 'tmux-plugins/tpm'`
`set -g @plugin 'tmux-plugins/tmux-sensible'`
`set -g @plugin 'tmux-plugins/tmux-resurrect'`
`set -g @plugin 'tmux-plugins/tmux-continuum'`
`set -g @plugin 'tmux-plugins/tmux-copycat'`
`set -g @plugin 'tmux-plugins/tmux-yank'`
`set -g @plugin 'tmux-plugins/tmux-battery'`
`set -g @plugin 'tmux-plugins/tmux-prefix-highlight'`

Thanks!

**Comment by baest** [comment]
Which version are you using? You might need to upgrade tmux

**Comment by peterdutton** [comment]
I'm using tmux 2.1 on Ubuntu 16.04LTS.

**Comment by baest** [comment]
Yes, I was using 2.3 and it didn't work. I've upgrade to 2.6 today and it works now.

**Comment by bruno-** [comment]
@peterdutton please upgrade to latest tmux version!
