### ISSUE TITLE
Prefix C-g doesn't match paths starting with ../

### ISSUE THREAD

**Issue by JonnyHaystack** [tmux-plugins/tmux-copycat#142]
Hi, this seems to be basically the same issue as #48 except while that issue has been fixed, the same issue is still present with the git status file matching.

![img-2019-07-19-673](https://user-images.githubusercontent.com/1266473/61541833-4724df00-aa38-11e9-9a63-2f315ebf09c9.png)

**Comment by JonnyHaystack** [comment]
Well I now see that there's been an open PR (#79) for 5 years to fix this issue. Not sure why it hasn't been merged.

**Comment by Lollipopster** [comment]
+ HERE, are you going to merge this PR ?

**Comment by bruno-** [comment]
#79 has been merged, sorry for the long wait.
I tested and this issue seems to be fixed. Please open another issue if this is still a problem.
