### ISSUE TITLE
plugin does not work (key binding issue)

### ISSUE THREAD

**Issue by mohitleo9** [tmux-plugins/tmux-copycat#40]
hey , I really like the idea of this plugin but it does not work for me with zsh

I get this error 
 zsh: command not found: G0:3

**Comment by labianchin** [comment]
I also had this issue.
Thanks @bruno- for figuring that out. This comment really help: https://github.com/tmux-plugins/tmux-copycat/issues/40#issuecomment-50958907
I would suggest adding the link to this issue in the _Limitation_ section of the `Readme.md`.

**Comment by bruno-** [comment]
Hey,
the limitations doc in now updated [link](https://github.com/tmux-plugins/tmux-copycat/blob/master/docs/limitations.md). I figured just restarting tmux server is the easiest thing to do so that's the suggestion.
