### ISSUE TITLE
copy-cat break my C-j shortcut

### ISSUE THREAD

**Issue by MrJJJ** [tmux-plugins/tmux-copycat#62]
I've got my tmux.conf set with : 
bind-key -n C-j select-pane -t :.+
bind-key -n C-k select-pane -t :.-

The problem is that after using copycat for the first time (after sourcing my tmux.conf), the C-j shortcut is broken (it simulates an <Enter> press). C-k still works prefectly.

**Comment by bruno-** [comment]
Hi,
can you please check this issue #60 and see if the fix proposed there works for you.
We'll probably have to do something about this though as this is the third report for the same issue.

**Comment by MrJJJ** [comment]
It works perfectly. Thanks very much for your help and this amazing plugin !

**Comment by bruno-** [comment]
Cool, glad that solved the problem!
