### ISSUE TITLE
Keybindings not working

### ISSUE THREAD

**Issue by bechampion** [tmux-plugins/tmux-copycat#67]
Hi List.
So I've installed copycat using the plugin manager it all goes well and installs , but non of the keybindings seem to working .. not a single one.

I've check the limitations and my setup seems fine, i got powerbar  but nothing too fancy:

[~]🌀 >bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.

[~]🌀 >tmux -V
tmux 1.9a

setw -g mode-keys vi
set -g default-terminal "xterm-256color"
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
setw -g mode-mouse on
set-option -g mouse-select-pane on
set -g mouse-resize-pane on
set-option -g pane-active-border-fg blue
source '/Users/jgarcia/.vim/bundle/powerline/powerline/bindings/tmux/powerline.conf'
 set -g @tpm_plugins '              \
   tmux-plugins/tpm                 \
   tmux-plugins/tmux-sensible       \
run-shell '~/.tmux/plugins/tpm/tpm'
set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  tmux-plugins/tmux-copycat    \
'

Thanks!

**Comment by bruno-** [comment]
Hey,
I think the plugin's setup in `tmux.conf` might be a little bit off.
Can you please try having this order at the very bottom of `tmux.conf`:

```bash
set -g @tpm_plugins ' \
  tmux-plugins/tpm \
  tmux-plugins/tmux-copycat \
  tmux-plugins/tmux-sensible \
'
run-shell '~/.tmux/plugins/tpm/tpm'
```

Please notice how the line `set -g @tpm_plugins...` comes before `run-shell '~/.tmux/plugins/tpm/tpm' `.
Also, all the plugins are listed under a single `@tpm_plugins` statement (this should not be set more than once in `tmux.conf`).

I think this should fix the issue so I'm going to close the issue. If it doesn't work, please reopen and I'll try to help.
