### ISSUE TITLE
weird behaviour

### ISSUE THREAD

**Issue by bechampion** [tmux-plugins/tmux-copycat#71]
After being happy with tmux-copycat for months now it seems to behave a bit erratic with the matches

when i do prefix /  and search for someting it highlights more than the match..

prefix C-u doesn't do anything at all either.

I've been playing with GREP_COLORS and other things but i don't think that could be an issue:

##start vimode history and term colors
setw -g mode-keys vi
set -g default-terminal "xterm-256color"
set-option -g history-limit 5000
##end
##start copy to clipboard
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
##end
##start mouse and others
setw -g mode-mouse on
set-option -g mouse-select-pane on
set -g mouse-resize-pane on
##end
##start key binding to move around
bind-key -n C-S-Up resize-pane -U 10
bind-key -n C-S-Down resize-pane -D 10
bind-key -n C-S-Left resize-pane -L 25
bind-key -n C-S-Right resize-pane -R 25
##end
##start status bar colors and possition
#set-option -g pane-active-border-fg "#4775A3"
set-option -g pane-active-border-fg blue
set-option -g message-bg "#393B3D"
set-option -g message-fg white
set-option -g pane-border-fg "#273646"
set-option -g status-position top    # position the status bar at top of screen

source '/Users/jgarcia/.vim/bundle/powerline/powerline/bindings/tmux/powerline.conf'
##end
##start TPM Pluginx
set -g @tpm_plugins ' \
 tmux-plugins/tpm \
 tmux-plugins/tmux-copycat \
 tmux-plugins/tmux-sensible \
'
run-shell '~/.tmux/plugins/tpm/tpm'
##end

**Comment by bechampion** [comment]
Hi Bruno I'm running 1.9a.
My laptop restarted yesterday for an update  ,  and when everything came back copycat was running just fine?
my copycat version is # v2.1.0, Jan 01, 2015
 it all works just fine now ... weird , but thanks!!

**Comment by bruno-** [comment]
Hey @bechampion,
yea, that's weird. Glad to hear everything is ok now.
I'll close the issue but please reopen if this happens again.
